version: '3.9'

services:
  #MongoDB service
  mongo_db:
    container_name: db_container
    image: mongo:latest
    restart: always
    # ports:
    #    - "27018:27017"
    volumes:
      - mongo_db:/data/db 

  
  #Node API service
  api:
    build: .
    ports:
      - 8080:7070
    environment:
        PORT: 7070
        MONGODB_URI : mongodb://localhost:27017/TSOA
        DB_NAME : TSOA
        NAME : TSOA_SERVER

    depends_on:
      - mongo_db

    

volumes:
  mongo_db: {}
